### ISSUE TITLE
License and citation files missing

### ISSUE THREAD

**Issue by javimangal** [wangzlab/population_airway_microbiome#2]
Hi, 

I noticed that this repository does not have an associated license nor citation file. May I suggest that the authors add a license file to this repository so that other scientists like myself know what can and cannot be done with the available data and code in this repository? 

License: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Citation: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by wangzlab** [comment]
A LICENCE file is created
